---
- name: Déploiement de l'application avec Docker Compose
  hosts: apps
  vars_files:
    - group_vars/apps.yml

  tasks:
    - name: Créer le dossier de déploiement
      file:
        path: "{{ app_directory }}"
        state: directory

    - name: Login au registre Docker privé
      # community.docker.docker_login:
      docker_login:
        registry: "{{ registry }}"
        username: "{{ registry_login }}"
        password: "{{ registry_password }}"

    - name: Copier docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: "{{ app_directory }}/docker-compose.yml"

    - name: Copier backend.env
      copy:
        src: backend.env
        dest: "{{ app_directory }}/backend.env"

    - name: Pull les images Docker
      command:
        cmd: "docker compose pull"
        chdir: "{{ app_directory }}"

    - name: Start les containers Docker
      command:
        cmd: "docker compose up -d --remove-orphans"
        chdir: "{{ app_directory }}"