name: Lint & Tests

on: 
  pull_request:
    branches: master
  push:

env:
  PYTHONPATH: ./src
  PYTHON_VERSION: "3.10"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8

      - name: Run pylint
        run: |
          pylint --fail-under=8 $(git ls-files '*.py')

      - name: Run flake8
        run: |
          flake8 .


  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run unit tests with pytest + coverage
        run: |
          pytest --cov --cov-fail-under=90 --cov-report=term-missing --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-${{ env.PYTHON_VERSION }}
          path: htmlcov
